### ISSUE TITLE
Will there be any updates for capturing new user agents

### ISSUE THREAD

**Issue by biswarup83** [arouel/uadetector#144]
Hi,

This was marvelous project on git. But we stopped getting any updates in the resources since 2014-11-09. Will there be newer updates possible to cover newer user agents since then ?

Thanks

**Comment by arouel** [comment]
Since the database is not open source anymore and the site http://user-agent-string.info/ is down it makes no sense to me to maintain it anymore. You can use the service at https://udger.com instead.
